(in-package #:cl-wasm-runtime.test)

(5am:def-suite cl-wasm-runtime.test.value-type
  :in cl-wasm-runtime.test)

(5am:in-suite cl-wasm-runtime.test.value-type)

(5am:test test-make-wasm-val-type
  (let ((i32 (make-wasm-valtype :wasm-i32))
	(i64 (make-wasm-valtype :wasm-i64))
	(f32 (make-wasm-valtype :wasm-f32))
	(f64 (make-wasm-valtype :wasm-f64))
	(any-ref (make-wasm-valtype :wasm-any-ref))
	(func-ref (make-wasm-valtype :wasm-func-ref)))
    (5am:is (eql :wasm-i32 (kind i32)))
    (5am:is (eql :wasm-i64 (kind i64)))
    (5am:is (eql :wasm-f32 (kind f32)))
    (5am:is (eql :wasm-f64 (kind f64)))
    (5am:is (eql :wasm-any-ref (kind any-ref)))
    (5am:is (eql :wasm-func-ref (kind func-ref)))))

(5am:test test-val-type-number
    (let ((i32 (make-wasm-valtype :wasm-i32))
	(i64 (make-wasm-valtype :wasm-i64))
	(f32 (make-wasm-valtype :wasm-f32))
	(f64 (make-wasm-valtype :wasm-f64))
	(any-ref (make-wasm-valtype :wasm-any-ref))
	(func-ref (make-wasm-valtype :wasm-func-ref)))
      (5am:is-true (number? i32))
      (5am:is-true (number? :wasm-i32))
      (5am:is-true (number? i64))
      (5am:is-true (number? :wasm-i64))
      (5am:is-true (number? f32))
      (5am:is-true (number? :wasm-f32))
      (5am:is-true (number? f64))
      (5am:is-true (number? :wasm-f64))
      (5am:is-false (number? any-ref))
      (5am:is-false (number? :wasm-any-ref))
      (5am:is-false (number? func-ref))
      (5am:is-false (number? :wasm-func-ref))))

(5am:test test-val-type-reference
    (let ((i32 (make-wasm-valtype :wasm-i32))
	(i64 (make-wasm-valtype :wasm-i64))
	(f32 (make-wasm-valtype :wasm-f32))
	(f64 (make-wasm-valtype :wasm-f64))
	(any-ref (make-wasm-valtype :wasm-any-ref))
	(func-ref (make-wasm-valtype :wasm-func-ref)))
      (5am:is-false (reference? i32))
      (5am:is-false (reference? :wasm-i32))
      (5am:is-false (reference? i64))
      (5am:is-false (reference? :wasm-i64))
      (5am:is-false (reference? f32))
      (5am:is-false (reference? :wasm-f32))
      (5am:is-false (reference? f64))
      (5am:is-false (reference? :wasm-f64))
      (5am:is-true (reference? any-ref))
      (5am:is-true (reference? :wasm-any-ref))
      (5am:is-true (reference? func-ref))
      (5am:is-true (reference? :wasm-func-ref))))
