(in-package #:cl-wasm-runtime.test)

(5am:def-suite cl-wasm-runtime.test.import-type
  :in cl-wasm-runtime.test)

(5am:in-suite cl-wasm-runtime.test.import-type)

(5am:test test-import-type-func-type
  (let* ((params '(:wasm-i32 :wasm-i64))
	 (results '(:wasm-f32))
	 (func-type (make-wasm-functype params results))
	 (namespace "foo")
	 (name "bar")
	 (import-type (make-wasm-importtype namespace name func-type))
	 (extern-type (extern-type import-type))
	 (func-type-from-extern-type (to-wasm-func-type extern-type)))
    (5am:is (string= namespace (namespace import-type)))
    (5am:is (string= name (name import-type)))
    (5am:is (eql :wasm-extern-func (kind extern-type)))
    (5am:is (= (length params) (size (params func-type-from-extern-type))))
    (5am:is (= (length results) (size (results func-type-from-extern-type))))))

(5am:test test-import-type-global-type
  (let* ((global-type (make-wasm-globaltype :wasm-i32 :mutable t))
	 (namespace "foo")
	 (name "bar")
	 (import-type (make-wasm-importtype namespace name global-type))
	 (extern-type (extern-type import-type))
	 (global-type-from-extern-type (to-wasm-global-type extern-type)))
    (5am:is (string= namespace (namespace import-type)))
    (5am:is (string= name (name import-type)))
    (5am:is (eql :wasm-extern-global (kind extern-type)))
    (5am:is (eql :wasm-i32 (kind (value-type global-type-from-extern-type))))
    (5am:is (mutable? global-type-from-extern-type))))

(5am:test test-import-type-table-type
  (let* ((min 1)
	 (max 7)
	 (limits (make-wasm-limits min max))
	 (table-type (make-wasm-tabletype :wasm-i32 limits))
	 (namespace "foo")
	 (name "bar")
	 (import-type (make-wasm-importtype namespace name table-type))
	 (extern-type (extern-type import-type))
	 (table-type-from-extern-type (to-wasm-table-type extern-type))
	 (limits-from-table-type (limits table-type-from-extern-type)))
    (5am:is (string= namespace (namespace import-type)))
    (5am:is (String= name (name import-type)))
    (5am:is (eql :wasm-extern-table (kind extern-type)))
    (5am:is (eql :wasm-i32 (kind (value-type table-type-from-extern-type))))
    (5am:is (= min (minimum limits-from-table-type)))
    (5am:is (= max (maximum limits-from-table-type)))))

(5am:test test-import-type-memory-type
  (let* ((min 1)
	 (max 7)
	 (limits (make-wasm-limits min max))
	 (memory-type (make-wasm-memorytype limits))
	 (namespace "foo")
	 (name "bar")
	 (import-type (make-wasm-importtype namespace name memory-type))
	 (extern-type (extern-type import-type))
	 (memory-type-from-extern-type (to-wasm-memory-type extern-type))
	 (limits-from-memory-type (limits memory-type-from-extern-type)))
    (5am:is (string= namespace (namespace import-type)))
    (5am:is (string= name (name import-type)))
    (5am:is (eql :wasm-extern-memory (kind extern-type)))
    (5am:is (= min (minimum limits-from-memory-type)))
    (5am:is (= max (maximum limits-from-memory-type)))))
